name: Static Checks

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read

jobs:
  clang-format:
    name: clang-format
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-format
        run: pipx install clang-format
      - name: Check formatting
        run: clang-format --dry-run --Werror $(git ls-files '*.cpp' '*.hpp' '*.h' '*.hip')
